version: "3"

services:
  my-composer:
    image: smart_sk2023:latest
    container_name: smart_sk
    # カレントディレクトリでイメージを構築
    build: .
    # カレントディレクトリをコンテナへマウント
    volumes:
      - ".:/var/www/html"
    ports:
      - 8085:80
    # プロセスを継続させてコンテナの正常終了を防ぐ
    # expose:
    #   - 9000
    stdin_open: true